name: Scheduled Cypress Run

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    - cron: '20 5,17 * * *'

jobs:
    cypress_run:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              submodules: true
          - name: Run install
            run: npm ci
          - name: Run cypress
            run: npm run cy:run
